name: Deploy a Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Subir archivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 46.202.183.217
          username: u668359514
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
